"""add warning_sent and exceeded_dent to budget table

Revision ID: 9bb943102da6
Revises: 1bbbd67c90c7
Create Date: 2026-06-02 12:50:15.685625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bb943102da6'
down_revision: Union[str, Sequence[str], None] = '1bbbd67c90c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budgets', sa.Column('warning_sent', sa.Boolean(), nullable=True))
    op.add_column('budgets', sa.Column('exceeded_sent', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('budgets', 'exceeded_sent')
    op.drop_column('budgets', 'warning_sent')
    # ### end Alembic commands ###
